# 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
import os

# 2. Set path

In [2]:
# set path for data files
path = r'C:\Users\Stony\OneDrive\CareerFoundry\Data Immersion Course\Instacart Basket Analysis'

# 3. Import dataset

In [18]:
# Import ords_prods_merged dataset
ords_prods_merged_updated = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merged_updated.pkl'))

# 4. Calculate mean of order_number

In [19]:
# Use groupby and agg functions to calculate mean of user_order_number
ords_prods_merged_updated.groupby('department_id').agg({'order_number' : ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

When looking at the entire dataframe there are more department_id numbers listed versus looking at the subset of data. Also, the mean numbers are higher for each department when looking at the entire dataframe.

# 5. Create loyalty flag for customers using transform() and loc()

In [20]:
# Use groupby and transform() functions with np.max to determine maximum order number for each user
ords_prods_merged_updated['max_order'] = ords_prods_merged_updated.groupby(['user_id'])['order_number'].transform(np.max)

C:\Users\Stony\AppData\Local\Temp\ipykernel_7072\1886825506.py:2: FutureWarning: The provided callable <function max at 0x000002EBCAA35260> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merged_updated['max_order'] = ords_prods_merged_updated.groupby(['user_id'])['order_number'].transform(np.max)

In [21]:
# Validate the function updated our dataframe
ords_prods_merged_updated.head(20)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,first_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,False,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,False,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,False,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,True,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,False,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,False,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,26
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,False,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,False,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,False,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,20
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,False,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,20
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,NaN,True,1,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,10
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.0,False,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.0,False,3,1,both,Mid-range product,Least busy,Slowest days,Most orders,43
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.0,False,4,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,43
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.0,False,8,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,13
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,6.0,False,18,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,10.0,False,12,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,7.0,False,10,0,both,Mid-range product,Regularly busy,Regularly busy,Fewest orders,28
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,6.0,False,9,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,28
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,14.0,False,9,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28

In [22]:
# Use loc() function to make loyalty flag column with the given criteria of > 40 orders is a loyal customer
ords_prods_merged_updated.loc[ords_prods_merged_updated['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [24]:
# Use loc() function to make loyalty flag column with the given criteria of between 10 and 40 orders is a regular customer
ords_prods_merged_updated.loc[(ords_prods_merged_updated['max_order'] <= 40) & (ords_prods_merged_updated['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [25]:
# Use loc() function to make loyalty flag column with the given criteria of < 10 orders is a new customer
ords_prods_merged_updated.loc[ords_prods_merged_updated['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [27]:
# Validate new column data and frequency of values
ords_prods_merged_updated['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [28]:
# Validate updated dataframe headings
ords_prods_merged_updated.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,...,first_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,False,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,False,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,False,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,True,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,False,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3,New customer

# 6. Investigate spending habits of customer groups

In [29]:
# Use groupby and agg() functions to determine basic statistics of spending habits by loyalty group
ords_prods_merged_updated.groupby('loyalty_flag').agg({'prices' : ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

According to the data, new customers spend approximately 3 dollars more on average then a loyal customer.

# 7. Create a spending flag for each user based on the average price across all of their orders

In [30]:
# Use the transform() function to determine the mean price of products purchased by each user
ords_prods_merged_updated['mean_product_price'] = ords_prods_merged_updated.groupby(['user_id'])['prices'].transform(np.mean)

C:\Users\Stony\AppData\Local\Temp\ipykernel_7072\3869908430.py:2: FutureWarning: The provided callable <function mean at 0x000002EBCAA35C60> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  ords_prods_merged_updated['mean_product_price'] = ords_prods_merged_updated.groupby(['user_id'])['prices'].transform(np.mean)

In [31]:
# Validate the new column was created successfully and only view it and user_id
ords_prods_merged_updated[['user_id', 'mean_product_price']].head(20)

    user_id  mean_product_price
0       138            6.935811
1       138            6.935811
2       709            7.930208
3       764            4.972414
4       764            4.972414
5       777            6.935398
6       825            5.957576
7       910            6.680000
8      1052            7.162500
9      1052            7.162500
10     1379            5.813636
11     1480            5.081633
12     1480            5.081633
13     1480            5.081633
14     1494            6.803797
15     1494            6.803797
16     1494            6.803797
17     1540            6.607122
18     1540            6.607122
19     1540            6.607122

In [32]:
# Create spending_flag column using loc() with criteria of 10 or more being a high spender
ords_prods_merged_updated.loc[ords_prods_merged_updated['mean_product_price'] >= 10, 'spending_flag'] = 'High spender'

In [33]:
# Create spending_flag column using loc() with criteria of lass than 10 being a low spender
ords_prods_merged_updated.loc[ords_prods_merged_updated['mean_product_price'] < 10, 'spending_flag'] = 'Low spender'

In [35]:
# Validate new column created successfully and check frequency of new column
ords_prods_merged_updated['spending_flag'].value_counts(dropna = False)

spending_flag
Low spender     31770614
High spender      634245
Name: count, dtype: int64

In [36]:
# View column headers of only the user_id, mean_relevant_price, and spending_flag columns
ords_prods_merged_updated[['user_id', 'mean_product_price', 'spending_flag']].head(20)

    user_id  mean_product_price spending_flag
0       138            6.935811   Low spender
1       138            6.935811   Low spender
2       709            7.930208   Low spender
3       764            4.972414   Low spender
4       764            4.972414   Low spender
5       777            6.935398   Low spender
6       825            5.957576   Low spender
7       910            6.680000   Low spender
8      1052            7.162500   Low spender
9      1052            7.162500   Low spender
10     1379            5.813636   Low spender
11     1480            5.081633   Low spender
12     1480            5.081633   Low spender
13     1480            5.081633   Low spender
14     1494            6.803797   Low spender
15     1494            6.803797   Low spender
16     1494            6.803797   Low spender
17     1540            6.607122   Low spender
18     1540            6.607122   Low spender
19     1540            6.607122   Low spender

# 8. Determine frequent versus non-frequent customers

In [38]:
# Use groupby and transform() functions to determine median number of days between orders for each user
ords_prods_merged_updated['median_days_between_orders'] = ords_prods_merged_updated.groupby(['user_id'])['days_since_last_order'].transform(np.median)

C:\Users\Stony\AppData\Local\Temp\ipykernel_7072\28070995.py:2: FutureWarning: The provided callable <function median at 0x000002EBCAB75B20> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  ords_prods_merged_updated['median_days_between_orders'] = ords_prods_merged_updated.groupby(['user_id'])['days_since_last_order'].transform(np.median)

In [39]:
# Validate new column created successfully and view column headers for user_id, days_since_last_order, and new column
ords_prods_merged_updated[['user_id', 'days_since_last_order', 'median_days_between_orders']].head(20)

    user_id  days_since_last_order  median_days_between_orders
0       138                    3.0                         8.0
1       138                   20.0                         8.0
2       709                    6.0                         8.0
3       764                    NaN                         9.0
4       764                    9.0                         9.0
5       777                   26.0                        11.0
6       825                   30.0                        20.0
7       910                   30.0                         6.0
8      1052                   19.0                        10.0
9      1052                   15.0                        10.0
10     1379                    NaN                        20.0
11     1480                    7.0                         7.0
12     1480                    7.0                         7.0
13     1480                   12.0                         7.0
14     1494                    2.0                         7.0
15     1494                    6.0                         7.0
16     1494                   10.0                         7.0
17     1540                    7.0                         7.0
18     1540                    6.0                         7.0
19     1540                   14.0                         7.0

In [40]:
# Create order frequency flag using loc() function based on the criteria if median_days_between_orders is > 20 then the user is a non-frequent customer
ords_prods_merged_updated.loc[ords_prods_merged_updated['median_days_between_orders'] > 20, 'order_frequency'] = 'Non-frequent customer'

In [41]:
# Create order frequency flag using loc() function based on the criteria if median_days_between_orders is between 10 and 20 then the user is a regular customer
ords_prods_merged_updated.loc[(ords_prods_merged_updated['median_days_between_orders'] <= 20) & (ords_prods_merged_updated['median_days_between_orders'] > 10), 'order_frequency'] = 'Regular customer'

In [42]:
# Create order frequency flag using loc() function based on the criteria if median_days_between_orders is less than 10 then the user is a frequent customer
ords_prods_merged_updated.loc[ords_prods_merged_updated['median_days_between_orders'] <= 10, 'order_frequency'] = 'Frequent customer'

In [43]:
# Validate new column was created successfully and check value counts of new order_frequency column
ords_prods_merged_updated['order_frequency'].value_counts(dropna = False)

order_frequency
Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: count, dtype: int64

There are rows that have not been labeled after our functions. This could be customers with only one order with Instacart and no other orders, which would be reflected in the not a number seen in the order_frequency values above.

In [45]:
# Run a datacheck on the column headers to ensure all headers are correct
ords_prods_merged_updated.head(50)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_product_price,spending_flag,median_days_between_orders,order_frequency
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,8.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,...,Mid-range product,Regularly busy,Busiest days,Average orders,26,Regular customer,6.935398,Low spender,11.0,Regular customer
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,...,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,5.957576,Low spender,20.0,Regular customer
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,...,Mid-range product,Regularly busy,Slowest days,Most orders,12,Regular customer,6.680000,Low spender,6.0,Frequent customer
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,...,Mid-range product,Regularly busy,Busiest days,Average orders,20,Regular customer,7.162500,Low spender,10.0,Frequent customer
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,...,Mid-range product,Regularly busy,Busiest days,Most orders,20,Regular customer,7.162500,Low spender,10.0,Frequent customer
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,...,Mid-range product,Regularly busy,Regularly busy,Most orders,10,New customer,5.813636,Low spender,20.0,Regular customer
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,...,Mid-range product,Regularly busy,Slowest days,Most orders,43,Loyal customer,5.081633,Low spender,7.0,Frequent customer
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,...,Mid-range product,Least busy,Slowest days,Most orders,43,Loyal customer,5.081633,Low spender,7.0,Frequent customer
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,...,Mid-range product,Regularly busy,Regularly busy,Most orders,43,Loyal customer,5.081633,Low spender,7.0,Frequent customer
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,...,Mid-range product,Regularly busy,Slowest days,Most orders,13,Regular customer,6.803797,Low spender,7.0,Frequent customer
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,...,Mid-range product,Regularly busy,Regularly busy,Average orders,13,Regular customer,6.803797,Low spender,7.0,Frequent customer
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,...,Mid-range product,Regularly busy,Regularly busy,Average orders,13,Regular customer,6.803797,Low spender,7.0,Frequent customer
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,...,Mid-range product,Regularly busy,Regularly busy,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,...,Mid-range product,Regularly busy,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,...,Mid-range product,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,2,...,Mid-range product,Regularly busy,Regularly busy,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,23,...,Mid-range product,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,3,...,Mid-range product,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,14,...,Mid-range product,Regularly busy,Busiest days,Most orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,14,...,Mid-range product,Regularly busy,Busiest days,Most orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,21,...,Mid-range product,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,22,...,Mid-range product,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,22,...,Mid-range product,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,20,...,Mid-range product,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,22,...,Mid-range product,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,22,...,Mid-range product,Least busy,Slowest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,19,...,Mid-range product,Regularly busy,Regularly busy,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,1,...,Mid-range product,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,21,...,Mid-range product,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,12,...,Mid-range product,Regularly busy,Regularly busy,Most orders,4,New customer,7.123529,Low spender,2.0,Frequent customer
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,10,...,Mid-range product,Regularly busy,Regularly busy,Most orders,4,New customer,7.123529,Low spender,2.0,Frequent customer
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,17,...,Mid-range product,Least busy,Slowest days,Average orders,4,New customer,7.123529,Low spender,2.0,Frequent customer
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,9,...,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,13,...,Mid-range product,Busiest day,Busiest days,Most orders,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,9,...,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
40,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,8,0,17,...,Mid-range product,Busiest day,Busiest days,Average orders,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
41,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,9,4,15,...,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
42,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,1,0,14,...,Mid-range product,Busiest day,Busiest days,Most orders,10,New customer,7.377143,Low spender,13.0,Regular customer
43,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,7,1,16,...,Mid-range product,Regularly busy,Busiest days,Most orders,23,Regular customer,8.054153,Low spender,7.0,Frequent customer
44,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,24,1,8,...,Mid-range product,Regularly busy,Busiest days,Average orders,25,Regular customer,8.353793,Low spender,11.0,Regular customer
45,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,5,3,10,...,Mid-range product,Regularly busy,Slowest days,Most orders,13,Regular customer,6.452800,Low spender,7.0,Frequent customer
46,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,1,2,20,...,Mid-range product,Regularly busy,Regularly busy,Average orders,5,New customer,7.960606,Low spender,28.0,Non-frequent customer
47,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,4,2,10,...,Mid-range product,Regularly busy,Regularly busy,Most orders,6,New customer,6.322222,Low spender,18.0,Regular customer
48,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,1,1,14,...,Mid-range product,Regularly busy,Busiest days,Most orders,3,New customer,7.511111,Low spender,21.0,Non-frequent customer
49,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,2,1,10,...,Mid-range product,Regularly busy,Busiest days,Most orders,42,Loyal customer,7.441100,Low spender,7.0,Frequent customer

# 9. Export data

In [46]:
# Export ords_prods_merged_updated as pickle file 
ords_prods_merged_updated.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_derived.pkl'))